In [39]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

from skimage.transform import resize
from skimage.io import imread

import os
import matplotlib.pyplot as plt
import seaborn as sns

import pickle

In [6]:
datadir = 'images/'
categories = ['ChickenHead', 'ElephantHead']

flat_data_arr = []
target_arr = []

for i in categories:
    print('loading... category: ', i)
    path = os.path.join (datadir, i)
    for img in os.listdir (path):
        img_array = imread (os.path.join (path, img))
        img_resized = resize (img_array, (150, 150, 3))
        flat_data_arr.append (img_resized.flatten())
        target_arr.append (categories.index(i))
    print("loaded category ", i, " successfully")
    

loading... category:  ChickenHead
loaded category  ChickenHead  successfully
loading... category:  ElephantHead
loaded category  ElephantHead  successfully


In [7]:
flat_data = np.array (flat_data_arr)
target = np.array (target_arr)

df = pd.DataFrame (flat_data)
df['Target'] = target

df.head()

0         1         2         3         4         5         6  \
0  0.258824  0.258824  0.219608  0.231373  0.231373  0.192157  0.168627   
1  0.121569  0.227451  0.105882  0.129412  0.227451  0.113725  0.176471   
2  0.415686  0.698039  0.258824  0.384314  0.666667  0.235294  0.349020   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.784314  0.729412  0.623529  0.776471  0.721569  0.615686  0.737255   

          7         8         9  ...     67491     67492     67493     67494  \
0  0.168627  0.129412  0.180392  ...  0.321569  0.321569  0.290196  0.301961   
1  0.254902  0.149020  0.219608  ...  0.784314  0.670588  0.513725  0.772549   
2  0.619608  0.203922  0.321569  ...  0.423529  0.615686  0.266667  0.435294   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4  0.682353  0.576471  0.690196  ...  0.717647  0.643137  0.517647  0.725490   

      67495     67496     67497     67498     67499  Target  
0  0.301961  0.270588  0.290196  0.290196  0.258824       0  
1  0.658824  0.501961  0.768627  0.654902  0.498039       0  
2  0.627451  0.270588  0.380392  0.572549  0.215686       0  
3  0.000000  0.000000  0.000000  0.000000  0.000000       0  
4  0.650980  0.525490  0.721569  0.647059  0.521569       0  

[5 rows x 67501 columns]

In [8]:
X = df.values[:, :-1]
Y = df.values[:, -1]

xtrain, xtest, ytrain, ytest = train_test_split (X, Y, test_size = 0.2, random_state=47)

In [9]:
param_grid = {'C': [10, 100], 'gamma': [0.0001, 0.001, 0.1, 1, 10], 'kernel': ['rbf', 'poly']}
svc = SVC()

model = GridSearchCV (svc, param_grid)
model.fit(xtrain, ytrain)


GridSearchCV(estimator=SVC(),
             param_grid={'C': [10, 100], 'gamma': [0.0001, 0.001, 0.1, 1, 10],
                         'kernel': ['rbf', 'poly']})

In [10]:
print (model.best_params_)
ypred_train = model.predict (xtrain)
ypred_test = model.predict (xtest)

print ('Train Accuracy: ', accuracy_score (ypred_train, ytrain))
print ('Test Accuracy', accuracy_score (ypred_test, ytest))

{'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
Train Accuracy:  1.0
Test Accuracy 0.9


In [11]:
filename = 'chicken1.png'

img_array = imread (filename)
img_resized = resize (img_array, (150, 150, 3))
test_data = np.array (img_resized.flatten())
test_data = test_data.reshape(1, -1)
print (test_data.shape)

(1, 67500)


In [12]:
p = model.predict (test_data)
if p == 0: print ('ChickenHead')
elif p == 1: print('ElephantHead')

ChickenHead


In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [14]:
X = df.values[:, 1:]
Y = df.values[:, 0:]
print(X[0])

[0.25882353 0.21960784 0.23137255 ... 0.29019608 0.25882353 0.        ]


In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Columns: 67501 entries, 0 to Target
dtypes: float64(67500), int32(1)
memory usage: 103.0 MB


In [16]:
df.isna().sum()

0         0
1         0
2         0
3         0
4         0
         ..
67496     0
67497     0
67498     0
67499     0
Target    0
Length: 67501, dtype: int64

In [17]:
X = df.values[:, :-1]
Y = df.values[:, -1]

print(X)

X_train, X_test, y_train, y_test = train_test_split (X, Y, test_size = 0.2, random_state=1, shuffle = True)
#print (X.shape)
#print (X_train.shape)
#print (X_test.shape)

[[0.25882353 0.25882353 0.21960784 ... 0.29019608 0.29019608 0.25882353]
 [0.12156863 0.22745098 0.10588235 ... 0.76862745 0.65490196 0.49803922]
 [0.41568627 0.69803922 0.25882353 ... 0.38039216 0.57254902 0.21568627]
 ...
 [0.50980392 0.51764706 0.36078431 ... 0.65098039 0.48627451 0.25882353]
 [0.55294118 0.61568627 0.81568627 ... 0.22352941 0.29411765 0.2       ]
 [0.56078431 0.76470588 0.84705882 ... 0.29019608 0.58431373 0.25098039]]


In [18]:
scores = []
for k in range(1, 41):
    knn = KNeighborsClassifier (n_neighbors = k)
    knn.fit (X_train, y_train)
    
    y_pred = knn.predict (X_test)
    score = accuracy_score (y_pred, y_test)
    
    print("k=%d, accuracy=%.2f%%" % (k, score * 100))
    scores.append (score)
    
m = max (scores)
print('max accuracy: ', m, ' for k=', scores.index(m)+1)

k=1, accuracy=87.50%
k=2, accuracy=90.00%
k=3, accuracy=87.50%
k=4, accuracy=90.00%
k=5, accuracy=92.50%
k=6, accuracy=90.00%
k=7, accuracy=95.00%
k=8, accuracy=92.50%
k=9, accuracy=90.00%
k=10, accuracy=95.00%
k=11, accuracy=90.00%
k=12, accuracy=92.50%
k=13, accuracy=92.50%
k=14, accuracy=92.50%
k=15, accuracy=92.50%
k=16, accuracy=92.50%
k=17, accuracy=90.00%
k=18, accuracy=95.00%
k=19, accuracy=90.00%
k=20, accuracy=87.50%
k=21, accuracy=90.00%
k=22, accuracy=90.00%
k=23, accuracy=90.00%
k=24, accuracy=92.50%
k=25, accuracy=92.50%
k=26, accuracy=92.50%
k=27, accuracy=87.50%
k=28, accuracy=92.50%
k=29, accuracy=90.00%
k=30, accuracy=92.50%
k=31, accuracy=87.50%
k=32, accuracy=87.50%
k=33, accuracy=87.50%
k=34, accuracy=87.50%
k=35, accuracy=87.50%
k=36, accuracy=90.00%
k=37, accuracy=85.00%
k=38, accuracy=87.50%
k=39, accuracy=87.50%
k=40, accuracy=87.50%
max accuracy:  0.95  for k= 7


In [20]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [21]:
digits = load_digits()
X = digits.data
y = digits.target

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [23]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [25]:
y_pred = rfc.predict(X_test)

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        53
           1       0.96      0.98      0.97        50
           2       0.98      0.98      0.98        47
           3       1.00      0.94      0.97        54
           4       0.97      1.00      0.98        60
           5       0.96      0.97      0.96        66
           6       0.98      0.98      0.98        53
           7       0.98      0.98      0.98        55
           8       0.93      0.98      0.95        43
           9       0.98      0.95      0.97        59

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540



In [28]:
svm = SVC()
svm.fit(X_train, y_train)

# Evaluate the performance of the support vector machine classifier
y_pred_svm = svm.predict(X_test)
print("Classification report for Support Vector Machine Classifier:")
print(classification_report(y_test, y_pred_svm))

with open('svmModel.pkl', 'wb') as f:
    pickle.dump(svm, f)

Classification report for Support Vector Machine Classifier:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        47
           3       0.98      0.98      0.98        54
           4       1.00      1.00      1.00        60
           5       1.00      0.98      0.99        66
           6       0.98      1.00      0.99        53
           7       0.98      0.98      0.98        55
           8       0.95      0.98      0.97        43
           9       0.97      0.95      0.96        59

    accuracy                           0.99       540
   macro avg       0.99      0.99      0.99       540
weighted avg       0.99      0.99      0.99       540



In [29]:
abc = AdaBoostClassifier()
abc.fit(X_train, y_train)

# Evaluate the performance of the AdaBoost classifier
y_pred_abc = abc.predict(X_test)
print("Classification report for AdaBoost Classifier:")
print(classification_report(y_test, y_pred_abc))

with open('adaBoostModel.pkl', 'wb') as f:
    pickle.dump(abc, f)

Classification report for AdaBoost Classifier:
              precision    recall  f1-score   support

           0       0.98      0.91      0.94        53
           1       0.00      0.00      0.00        50
           2       0.00      0.00      0.00        47
           3       0.00      0.00      0.00        54
           4       0.50      0.05      0.09        60
           5       0.54      0.20      0.29        66
           6       0.36      0.91      0.52        53
           7       0.00      0.00      0.00        55
           8       0.15      0.98      0.26        43
           9       0.67      0.51      0.58        59

    accuracy                           0.34       540
   macro avg       0.32      0.35      0.27       540
weighted avg       0.34      0.34      0.27       540



C:\Users\Jada\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Jada\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Jada\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

# Evaluate the performance of the K-Nearest Neighbors classifier
y_pred_knn = knn.predict(X_test)
print("Classification report for K-Nearest Neighbors Classifier:")
print(classification_report(y_test, y_pred_knn))

with open('knnModel.pkl', 'wb') as f:
    pickle.dump(knn, f)

Classification report for K-Nearest Neighbors Classifier:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        47
           3       0.98      1.00      0.99        54
           4       0.98      1.00      0.99        60
           5       0.98      0.98      0.98        66
           6       1.00      1.00      1.00        53
           7       1.00      1.00      1.00        55
           8       1.00      1.00      1.00        43
           9       0.98      0.95      0.97        59

    accuracy                           0.99       540
   macro avg       0.99      0.99      0.99       540
weighted avg       0.99      0.99      0.99       540



In [33]:
nn = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000)
nn.fit(X_train, y_train)

# Evaluate the performance of the Neural Network classifier
y_pred_nn = nn.predict(X_test)
print("Classification report for Neural Network Classifier:")
print(classification_report(y_test, y_pred_nn))

with open('nnModel.pkl', 'wb') as f:
    pickle.dump(nn, f)

Classification report for Neural Network Classifier:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      0.96      0.98        50
           2       0.96      1.00      0.98        47
           3       0.98      0.94      0.96        54
           4       1.00      0.98      0.99        60
           5       0.97      0.97      0.97        66
           6       0.96      0.98      0.97        53
           7       1.00      0.98      0.99        55
           8       0.91      0.98      0.94        43
           9       0.97      0.97      0.97        59

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540



In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
rfc = RandomForestClassifier(random_state=42)
rfc.fit(X_train, y_train)

# Evaluate random forest classifier
y_pred = rfc.predict(X_test)
print("Random Forest Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred))

Random Forest Classifier
Accuracy: 0.9740740740740741


In [41]:
svm = SVC(random_state=42)
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
print("Support Vector Machine")
print("Accuracy:", accuracy_score(y_test, y_pred))

Support Vector Machine
Accuracy: 0.9796296296296296


In [42]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print("K-Nearest Neighbors")
print("Accuracy:", accuracy_score(y_test, y_pred))

K-Nearest Neighbors
Accuracy: 0.975925925925926


In [50]:
ada = AdaBoostClassifier(n_estimators=50)
ada.fit(X_train, y_train)

y_pred = ada.predict(X_test)
print("AdaBoost")
print("Accuracy:", accuracy_score(y_test, y_pred))

AdaBoost
Accuracy: 0.34074074074074073
